plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\david\\Documents\\Healthcare_Uncharted_Site\\_site"
publishOrigin = "ui"
commandOrigin = "ui"
command = "eleventy"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]