// build-icons.js — the icon subset.
//
// The site loaded the whole Lucide UMD bundle from unpkg on EVERY page: 80 KB over
// the wire, 355 KB for the browser to parse, ~1,500 icons, of which this site uses
// 96. Plus a third-party DNS and TLS round trip before a single icon could render,
// which on cellular is the part you actually feel.
//
// This scans src/ for every data-lucide name, pulls just those icons out of the
// `lucide` devDependency, and writes a self-hosted file that reimplements
// lucide.createIcons() with the SAME contract (verified in a browser against the
// real library, 2026-09-20):
//   - <svg> replaces the placeholder element
//   - base attrs: xmlns, width/height 24, viewBox 0 0 24 24, fill none,
//     stroke currentColor, stroke-width 2, stroke-linecap/linejoin round
//   - the placeholder's OWN attributes override those (cards ship width="16")
//   - data-lucide is preserved on the svg
//   - class becomes "lucide lucide-<name>" plus any classes the placeholder had
//
// Run: node scripts/build-icons.js   (also runs as part of npm run build)
// tests/icons.test.js fails the build if a name used in src/ is missing here.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(SRC, 'assets', 'js', 'hu-icons.js');

/** every file that could carry a data-lucide placeholder */
function walk(dir, hits = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { walk(p, hits); continue; }
    if (/\.(njk|html|js)$/i.test(e.name)) hits.push(p);
  }
  return hits;
}

/** kebab name as authored -> the package's PascalCase export (bar-chart-2 -> BarChart2) */
const pascal = (kebab) => kebab.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');

function usedNames() {
  const names = new Set();
  for (const f of walk(SRC)) {
    const txt = fs.readFileSync(f, 'utf8');
    for (const m of txt.matchAll(/data-lucide=["']([a-z0-9-]+)["']/g)) names.add(m[1]);
  }
  return [...names].sort();
}

function build() {
  const lucide = require('lucide');
  const names = usedNames();
  const icons = {};
  const missing = [];

  for (const n of names) {
    const data = lucide[pascal(n)];
    if (!data || !Array.isArray(data)) { missing.push(n); continue; }
    // data is ["svg", baseAttrs, children]; only the children vary per icon
    icons[n] = data[2];
  }

  if (missing.length) {
    console.error('icons: NOT FOUND in the lucide package: ' + missing.join(', '));
    console.error('  (a typo in a data-lucide attribute, or an icon renamed upstream)');
    process.exit(1);
  }

  const body = `/* GENERATED by scripts/build-icons.js — do not edit.
   ${names.length} icons, the ones this site actually uses. Replaces the 355 KB
   Lucide UMD bundle that used to load from unpkg on every page. Regenerate with
   \`node scripts/build-icons.js\` after adding a new data-lucide name. */
(function () {
  var NS = 'http://www.w3.org/2000/svg';
  var BASE = {
    xmlns: NS, width: '24', height: '24', viewBox: '0 0 24 24', fill: 'none',
    stroke: 'currentColor', 'stroke-width': '2',
    'stroke-linecap': 'round', 'stroke-linejoin': 'round'
  };
  var I = ${JSON.stringify(icons)};

  function createIcons() {
    var nodes = document.querySelectorAll('[data-lucide]');
    for (var i = 0; i < nodes.length; i++) {
      var el = nodes[i];
      if (el.tagName.toLowerCase() === 'svg') continue;   // already rendered
      var name = el.getAttribute('data-lucide');
      var kids = I[name];
      if (!kids) continue;                                 // unknown name: leave the placeholder
      var svg = document.createElementNS(NS, 'svg');
      for (var k in BASE) svg.setAttribute(k, BASE[k]);
      for (var a = 0; a < el.attributes.length; a++) {     // placeholder attrs win
        var at = el.attributes[a];
        if (at.name === 'class') continue;
        svg.setAttribute(at.name, at.value);
      }
      var own = el.getAttribute('class');
      svg.setAttribute('class', 'lucide lucide-' + name + (own ? ' ' + own : ''));
      for (var c = 0; c < kids.length; c++) {
        var node = document.createElementNS(NS, kids[c][0]);
        var attrs = kids[c][1] || {};
        for (var k2 in attrs) node.setAttribute(k2, attrs[k2]);
        svg.appendChild(node);
      }
      if (el.parentNode) el.parentNode.replaceChild(svg, el);
    }
  }

  window.lucide = { createIcons: createIcons };
})();
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body, 'utf8');
  const kb = (fs.statSync(OUT).size / 1024).toFixed(1);
  const gz = (require('zlib').gzipSync(body, { level: 9 }).length / 1024).toFixed(1);
  console.log('icons: ' + names.length + ' icons -> ' + path.relative(ROOT, OUT) + '  ' + kb + ' KB raw, ' + gz + ' KB gzipped');
}

build();
