module.exports = [

  // ── LIVE TOOLS ──────────────────────────────────────────────────────────────

  {
    id:          'multi-lens-map',
    cluster:     'maps-systems',
    keys:        ['population health', 'state data', 'county data', 'life expectancy', 'uninsured', 'medicaid', 'public health map'],
    status:      'live',
    featured:    true,
    title:       'U.S. Pop Health Multi-Lens Map',
    desc:        'U.S. state-level healthcare data across six lenses: patient, clinical, operations, payer, policy, and baseline context. One map, every angle.',
    url:         '/tools/multi-lens-map/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-blue',
    mark:        'MAP',
    markClass:   'mark-blue',
    tags:        ['State Map', '5 Lenses', 'Interactive'],
    motif:       'compass-rose',
    ps:          ['p1', 'p2a', 'p2b', 'p3', 'p4'],
    labNode:     'american-4ps-map'
  },

  {
    id:          'iceberg-map',
    cluster:     'maps-systems',
    keys:        ['big picture', 'system layers', 'how healthcare works', 'payers', 'policy'],
    status:      'live',
    featured:    true,
    title:       'The Healthcare Iceberg Map',
    desc:        'An interactive map of the full U.S. healthcare system. All 8 layers visible at once, from patient experience to the policy and financial forces underneath.',
    url:         '/tools/iceberg-map/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-teal',
    mark:        'HI',
    markClass:   'mark-teal',
    tags:        ['System Map', '8 Layers', 'Interactive'],
    motif:       'compass-rose',
    ps:          ['p1', 'p2a', 'p2b', 'p3', 'p4'],
    labNode:     'healthcare_iceberg_map'
  },

  {
    id:          'vendor-directory',
    cluster:     'maps-systems',
    keys:        ['vendors', 'companies', 'ehr market', 'epic', 'cerner', 'oracle health', 'ai companies', 'market share'],
    status:      'live',
    featured:    true,
    title:       'Healthcare Vendor Directory',
    desc:        'A searchable, filterable directory of major healthcare technology vendors. What sector they operate in, which layers of the system they touch, and whether their technology is proven, emerging, or cautionary.',
    url:         '/tools/vendor-directory/',
    type:        'reference',
    badge:       'Reference',
    badgeClass:  'badge-reference',
    bandClass:   'tc-band-purple',
    mark:        'VD',
    markClass:   'mark-purple',
    tags:        ['Vendors', 'AI', 'Healthcare Tech'],
    motif:       'network',
    ps:          ['p2a', 'p2b', 'p3'],
    labNode:     'vendor-directory'
  },

  {
    id:          'hospital-map',
    cluster:     'maps-systems',
    keys:        ['hospital departments', 'units', 'floors', 'who works where', 'icu', 'emergency department'],
    status:      'live',
    featured:    true,
    title:       'Hospital Blueprint',
    desc:        'Interactive cross-section of a modern hospital. Every unit, every floor, every service line. Click any department to see who staffs it, how patients move through it, how it bills, and what happens when it breaks.',
    url:         '/tools/hospital-map/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-teal',
    mark:        'HB',
    markClass:   'mark-teal',
    tags:        ['Hospital Ops', 'Departments', 'Interactive'],
    motif:       'compass-rose',
    ps:          ['p1', 'p2a', 'p3'],
    labNode:     'hospital-map'
  },

  {
    id:          'sql-mystery',
    cluster:     'learn-play',
    keys:        ['sql', 'database', 'queries', 'data model', 'practice', 'game', 'ehr tables'],
    status:      'live',
    featured:    true,
    title:       'Clinical SQL Mystery',
    desc:        'Learn the Patient → Encounter → Clinical Event data model by solving a real clinical mystery using SQL queries against an Epic-style database. Four cases, escalating difficulty. No experience needed.',
    url:         '/tools/sql-mystery/',
    type:        'lab',
    badge:       'Game',
    badgeClass:  'badge-lab',
    bandClass:   'tc-band-amber',
    mark:        'SQL',
    markClass:   'mark-amber',
    tags:        ['SQL', 'EHR', 'Beginner-friendly'],
    ps:          ['p2a', 'p2b'],
    labNode:     'sql-mystery'
  },

  {
    id:          'operators-map',
    cluster:     'maps-systems',
    keys:        ['hospitals near me', 'facilities', 'dialysis', 'pharmacies', 'surgery centers', 'cms data', 'health systems'],
    status:      'live',
    featured:    true,
    title:       'U.S. Hospital Operations Map',
    desc:        'A live national map of U.S. healthcare infrastructure from CMS data. Stack hospitals, dialysis, surgery centers, pharmacies, and equipment suppliers as layers; drill from states to counties to a single facility; draw your own search area; let the map find your county.',
    url:         '/tools/operators-map/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-blue',
    mark:        'OP',
    markClass:   'mark-blue',
    tags:        ['Facility Map', 'Systems', 'CMS Data'],
    motif:       'compass-rose',
    ps:          ['p2a', 'p2b', 'p3', 'p4'],
    labNode:     'healthcare-operators-map'
  },

  {
    id:          'assignment-compass',
    cluster:     'careers-pay',
    keys:        ['travel pay', 'stipend', 'taxes', 'cost of living', 'contract', 'relocation', 'per diem', 'take home pay', 'salary comparison', 'license', 'travel roles'],
    status:      'live',
    featured:    true,
    title:       'Assignment Compass',
    desc:        'Compare two locations before you take the job. Real state tax bracket math for all 50 states, projected monthly costs by category, GSA per diem for the assignment county, and the blind spots cost-of-living sites miss. Built for clinicians weighing offers and travel contracts.',
    url:         '/tools/assignment-compass/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-blue',
    mark:        'AC',
    markClass:   'mark-blue',
    tags:        ['Cost of Living', 'State Tax', 'Travel Contracts'],
    motif:       'compass-rose',
    ps:          ['p2a', 'p2b'],
    labNode:     'assignment-compass'
  },

  {
    id:          'career-tree',
    cluster:     'careers-pay',
    keys:        ['careers', 'credentials', 'certifications', 'become a nurse', 'respiratory therapist', 'pay ladder', 'travel roles', 'education paths'],
    status:      'live',
    featured:    true,
    title:       'Healthcare Career Tree',
    desc:        'A branching map of healthcare careers. Start with the roles that need no license, follow the credentials down through specialty, leadership, and technology, and pin your own path. A second track maps the patient journey from healthy to critical.',
    url:         '/tools/career-tree/',
    type:        'interactive',
    badge:       'Interactive',
    badgeClass:  'badge-interactive',
    bandClass:   'tc-band-teal',
    mark:        'CT',
    markClass:   'mark-teal',
    tags:        ['Careers', 'Roles', 'Pathways'],
    motif:       'compass-rose',
    ps:          ['p1', 'p2a', 'p2b'],
    labNode:     'healthcare-career-tree'
  }

];
